"""Figures and tables from the result files.

    python scripts/make_figures.py --results          # README figures + tables -> docs/figures/, docs/results_tables.md
    python scripts/make_figures.py --runs A B Bprime --out outputs/m3   # Phase 1 baselines (seen/held-out bars)

--results reads outputs/ambient_sweep/<run>/summary.json (small policy; seeds as <run>_s<k>),
outputs/colab/<run>/eval_*/summary.json (SmolVLA) and outputs/m2/3 (phone side-by-side videos).
"""
import argparse
import csv
import json
import os

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

LABELS = {"A": "A: sim only", "B": "B: sim + human (all)", "Bprime": "B′: sim + human (successful replays)",
          "oracle": "Oracle: sim, all 9 tasks"}


# validated categorical slots (dataviz reference palette, light): ambient = slot 1, naive = slot 2, clean only = slot 3
AMB, NAIVE, CLEAN = "#2a78d6", "#eb6834", "#1baf7a"
NOISE_RAMP = ["#86b6ef", "#2a78d6", "#104281"]          # sequential blue: 0.4x, 1x, 2x
INK, INK2, GRID, SURF = "#0b0b0b", "#52514e", "#e4e3df", "#fcfcfb"
SWEEP, COLAB = "outputs/ambient_sweep", "outputs/colab"


def style(ax):
    ax.set_facecolor(SURF)
    ax.spines[["top", "right"]].set_visible(False)
    ax.spines[["left", "bottom"]].set_color(INK2)
    ax.tick_params(colors=INK2, labelsize=8)
    ax.yaxis.grid(True, color=GRID, lw=0.8)
    ax.set_axisbelow(True)


def sweep(name):
    """(seen, blue) success in % over seeds of a small-policy run: arrays of shape [n_seeds]."""
    v = []
    for f in [os.path.join(SWEEP, name, "summary.json")] + sorted(
            __import__("glob").glob(os.path.join(SWEEP, f"{name}_s[0-9]", "summary.json"))):
        if os.path.exists(f):
            d = json.load(open(f))
            v.append((d["seen"]["success"] * 100, d["heldout"]["success"] * 100))
    return np.array(v).reshape(-1, 2)


def ms(name, col=1):
    v = sweep(name)
    if not len(v):
        return None
    return f"{v[:, col].mean():.1f} ± {v[:, col].std():.1f}" if len(v) > 1 else f"{v[0, col]:.1f}"


def end_labels(ax, items, x_pad, min_gap=5.0):
    """Direct labels at line ends, nudged apart vertically so they never overlap. items: [(x, y, text)]."""
    items = sorted(items, key=lambda t: t[1])
    ys = []
    for _, y, _ in items:
        ys.append(max(y, ys[-1] + min_gap) if ys else y)
    shift = max(0.0, (ys[-1] - items[-1][1]) / 2) if len(items) > 1 else 0.0   # recentre the stack
    for (x, y, txt), yl in zip(items, ys):
        ax.text(x + x_pad, yl - shift, txt, fontsize=7.5, color=INK, va="center")


def results(out_fig="docs/figures", out_md="docs/results_tables.md"):
    os.makedirs(out_fig, exist_ok=True)
    md = ["# Results tables (generated by `scripts/make_figures.py --results`)", ""]

    # 1) real phone replays on the small policy, 4 clean blue demos per task
    # (run, table label, short tick label, color, hatch)
    conds = [("C", "clean only", "clean\nonly", CLEAN, None),
             ("K4_P", "+ all phone, naive", "+ all phone\nnaive", NAIVE, None),
             ("K4_Pa75", "+ all phone, ambient t_min 75", "+ all phone\nambient", AMB, None),
             ("K4_Pok", "+ successful phone only, naive", "+ succ. only\nnaive", NAIVE, "//"),
             ("K4_Pok_a75", "+ successful phone only, ambient t_min 75", "+ succ. only\nambient", AMB, "//")]
    conds = [c for c in conds if len(sweep(c[0]))]
    md += ["## Small policy: real phone replays (4 clean blue demos per task)", "",
           "| training data | seeds | seen % | blue (held-out) % |", "|---|---|---|---|"]
    for n, lab, *_ in conds:
        md.append(f"| {lab} | {len(sweep(n))} | {ms(n, 0)} | {ms(n, 1)} |")
    md += ["", "Mean ± std over training seeds; 50 eval episodes per task and seed. \"Successful only\": the 37 of 48 "
           "replays that succeeded in sim.", ""]
    fig, axes = plt.subplots(1, 2, figsize=(9, 3.4), facecolor=SURF)
    for ax, col, title in ((axes[0], 1, "Blue (held-out) tasks"), (axes[1], 0, "Seen (red/green) tasks")):
        for i, (n, lab, _, c, hatch) in enumerate(conds):
            v = sweep(n)[:, col]
            ax.bar(i, v.mean(), 0.72, color=c, hatch=hatch, edgecolor=SURF if not hatch else "white", lw=0,
                   yerr=v.std() if len(v) > 1 else None, error_kw={"ecolor": INK2, "capsize": 3, "lw": 1})
            ax.text(i, v.mean() + (v.std() if len(v) > 1 else 0) + 2, f"{v.mean():.0f}", ha="center",
                    fontsize=8, color=INK)
        ax.set_xticks(range(len(conds)))
        ax.set_xticklabels([t for _, _, t, *_ in conds], fontsize=7, color=INK2)
        ax.set_ylim(0, 100)
        ax.set_title(title, fontsize=10, color=INK, loc="left")
        ax.set_ylabel("success %", fontsize=8, color=INK2)
        style(ax)
    fig.tight_layout()
    fig.savefig(os.path.join(out_fig, "phone_small_policy.png"), dpi=160, facecolor=SURF)
    plt.close(fig)

    # 2) best t_min vs noise level (synthetic noise, 4 clean blue demos per task)
    ts = [0, 10, 25, 50, 75, 90]
    levels = [("L1", "0.4× noise"), ("L2", "1× noise (phone-like)"), ("L3", "2× noise")]
    md += ["## Small policy: ambient t_min vs synthetic noise level (4 clean blue demos per task, blue %)", "",
           "| noise | naive | " + " | ".join(f"t_min {t}" for t in ts[1:]) + " |", "|---" * len(ts) + "|---|"]
    fig, ax = plt.subplots(figsize=(5.6, 3.6), facecolor=SURF)
    labs = []
    for (L, lab), c in zip(levels, NOISE_RAMP):
        y = [sweep(f"{L}_CN" if t == 0 else f"{L}_CNa{t}") for t in ts]
        md.append(f"| {lab} | " + " | ".join(ms(f"{L}_CN" if t == 0 else f"{L}_CNa{t}") or "–" for t in ts) + " |")
        pts = [(t, v[:, 1].mean()) for t, v in zip(ts, y) if len(v)]
        ax.plot([p[0] for p in pts], [p[1] for p in pts], color=c, lw=2, marker="o", ms=5,
                markeredgecolor=SURF, markeredgewidth=1.5)
        labs.append((pts[-1][0], pts[-1][1], lab))
    end_labels(ax, labs, 2)
    cl = sweep("C")[:, 1].mean()
    ax.axhline(cl, color=CLEAN, lw=1.5, ls="--")
    ax.text(1, cl + 1.5, f"clean only (noisy demos discarded): {cl:.0f}%", fontsize=7.5, color=INK)
    ax.set_xticks(ts)
    ax.set_xticklabels(["naive"] + [str(t) for t in ts[1:]])
    ax.set_xlim(-3, 120)
    ax.set_ylim(0, 100)
    ax.set_xlabel("ambient t_min (of T = 100)", fontsize=8, color=INK2)
    ax.set_ylabel("blue (held-out) success %", fontsize=8, color=INK2)
    ax.set_title("The best t_min rises with the noise level", fontsize=10, color=INK, loc="left")
    style(ax)
    fig.tight_layout()
    fig.savefig(os.path.join(out_fig, "noise_vs_tmin.png"), dpi=160, facecolor=SURF)
    plt.close(fig)
    md += ["", "Single seed except where ± is shown (3 seeds).", ""]

    # 3) clean-data scaling with and without the (synthetic, 1x) noisy demos
    ks = [(4, "C", "L2_CN", "L2_CNa90"), (8, "K8", "K8_N", "K8_Na90"), (12, "K12", "K12_N", "K12_Na90"),
          (24, "Ceil", "K24_N", "K24_Na90")]
    md += ["## Small policy: clean blue demos per task, with and without noisy demos (1× synthetic noise, blue %)", "",
           "| clean blue demos per task | clean only | + noisy, naive | + noisy, ambient t_min 90 |", "|---|---|---|---|"]
    fig, ax = plt.subplots(figsize=(5.6, 3.6), facecolor=SURF)
    labs = []
    for j, (lab, c) in enumerate((("clean only", CLEAN), ("+ noisy, naive", NAIVE), ("+ noisy, ambient t_min 90", AMB))):
        xs, ys = [], []
        for k, *names in ks:
            v = sweep(names[j])
            if len(v):
                xs.append(k)
                ys.append(v[:, 1].mean())
        ax.plot(xs, ys, color=c, lw=2, marker="o", ms=5, markeredgecolor=SURF, markeredgewidth=1.5)
        labs.append((xs[-1], ys[-1], lab))
    end_labels(ax, labs, 0.6)
    for k, *names in ks:
        md.append(f"| {k} | " + " | ".join(ms(n) or "–" for n in names) + " |")
    ax.set_xticks([4, 8, 12, 24])
    ax.set_xlim(2, 34)
    ax.set_ylim(0, 100)
    ax.set_xlabel("clean blue demos per task", fontsize=8, color=INK2)
    ax.set_ylabel("blue (held-out) success %", fontsize=8, color=INK2)
    ax.set_title("1× synthetic noise: noisy demos help only when clean data is scarce", fontsize=9.5, color=INK,
                 loc="left")
    style(ax)
    fig.tight_layout()
    fig.savefig(os.path.join(out_fig, "clean_scaling.png"), dpi=160, facecolor=SURF)
    plt.close(fig)
    md += ["", "Single seed except 4 clean (3 seeds for clean only, naive and ambient t_min 90).", ""]

    # 4) SmolVLA evals
    rows = []
    for f in sorted(__import__("glob").glob(os.path.join(COLAB, "*", "eval_*", "summary.json"))):
        d = json.load(open(f))
        run, ev = f.split(os.sep)[-3], f.split(os.sep)[-2]
        if run == "smoke":
            continue
        fmt = lambda k: (f"{d[k]['success'] * 100:.1f} [{d[k]['ci95'][0] * 100:.0f}, {d[k]['ci95'][1] * 100:.0f}]"
                         if k in d else "–")
        oc = d.get("outcomes", {}).get("seen", {})
        rows.append(f"| {run} | {ev.replace('eval_', '')} | {fmt('seen')} | {fmt('heldout')} | "
                    f"{oc['missed_grasp'] * 100:.0f}% |" if "missed_grasp" in oc else
                    f"| {run} | {ev.replace('eval_', '')} | {fmt('seen')} | {fmt('heldout')} | – |")
    md += ["## SmolVLA evaluations", "", "| run | eval (step, episodes/task, variant) | seen % [95% CI] | blue % [95% CI] | "
           "missed grasps (seen) |", "|---|---|---|---|---|"] + rows + [""]

    # 5) a phone/sim side-by-side still
    import imageio.v2 as imageio
    vid = os.path.join("outputs", "m2", "3", "blue_to_purple_02_side_by_side.mp4")
    if os.path.exists(vid):
        r = imageio.get_reader(vid)
        imageio.imwrite(os.path.join(out_fig, "phone_side_by_side.jpg"), r.get_data(int(r.count_frames() * 0.4)))
    with open(out_md, "w") as fh:
        fh.write("\n".join(md) + "\n")
    print("wrote", out_fig, out_md)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--runs", nargs="+", default=["A", "B", "Bprime"])
    p.add_argument("--out", default="outputs/m3")
    p.add_argument("--results", action="store_true", help="README figures + tables from the current result files")
    a = p.parse_args()
    if a.results:
        return results()
    res = {}
    for r in a.runs:
        f = os.path.join(a.out, r, "summary.json")
        if os.path.exists(f):
            with open(f) as fh:
                res[r] = json.load(fh)
        else:
            print(f"skipping {r}: {f} not found")
    if not res:
        return
    lines = ["| run | seen tasks | held-out tasks |", "|---|---|---|"]
    with open(os.path.join(a.out, "results.csv"), "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["run", "seen", "seen_lo", "seen_hi", "heldout", "heldout_lo", "heldout_hi", "n_seen", "n_heldout"])
        for r, s in res.items():
            S, Hd = s["seen"], s["heldout"]
            w.writerow([r, S["success"], *S["ci95"], Hd["success"], *Hd["ci95"], S["n"], Hd["n"]])
            fmt = lambda d: f"{d['success'] * 100:.0f}% [{d['ci95'][0] * 100:.0f}–{d['ci95'][1] * 100:.0f}]"
            lines.append(f"| {LABELS.get(r, r)} | {fmt(S)} | {fmt(Hd)} |")
    table = "\n".join(lines)
    with open(os.path.join(a.out, "results.md"), "w") as fh:
        fh.write(table + "\n\nSuccess rate with 95% Wilson confidence interval.\n")
    print(table)

    fig, ax = plt.subplots(figsize=(1.6 + 1.3 * len(res), 3.6))
    x = np.arange(len(res))
    wd = 0.38
    for k, (split, col) in enumerate((("seen", "#4C72B0"), ("heldout", "#DD8452"))):
        m = np.array([res[r][split]["success"] for r in res])
        lo = np.array([res[r][split]["ci95"][0] for r in res])
        hi = np.array([res[r][split]["ci95"][1] for r in res])
        ax.bar(x + (k - 0.5) * wd, m, wd, yerr=[m - lo, hi - m], capsize=3, color=col,
               label="seen tasks" if split == "seen" else "held-out tasks")
    ax.set_xticks(x)
    ax.set_xticklabels([LABELS.get(r, r).split(":")[0] for r in res])
    ax.set_ylim(0, 1)
    ax.set_ylabel("success rate")
    ax.legend(frameon=False, fontsize=8)
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout()
    fig.savefig(os.path.join(a.out, "baselines.png"), dpi=150)
    print("wrote", os.path.join(a.out, "baselines.png"))


if __name__ == "__main__":
    main()
